### ISSUE TITLE
Spaltenbreite Beschreibung / Bedienung unglücklich

### ISSUE THREAD

**Issue by ruhr70** [ioBroker/ioBroker.scenes#1]
Bei der Spalte "Beschreibung" sind in der Tabellen Übersicht nur die ersten drei Buchstaben sichtbar. Die Spaltengröße lässt sich nicht ändern.

Hier wäre es schöner, dass die Breite der Spate "Beschreibung" größer wäre oder die Spaltenbreite anpassbar ist.

**Comment by Homoran** [comment]
Sollte mit Admin v3 erledigt sein

**Comment by Apollon77** [comment]
Bitte erneut öffnen wenn noch aktuell mit Admin3 auftritt
