### ISSUE TITLE
Übersetzung der Spaltenüberschrift

### ISSUE THREAD

**Issue by lubeda** [ioBroker/ioBroker.scenes#10]
im Deutschen steht "Bedienung" im Youtubevideo  (https://www.youtube.com/watch?v=_8rpKHz5AIw) steht aber condition als "Bedingung".

Auserdem sehe ich keine hinterlegte Funktion. Selbst wenn ich einen Trigger hinterlege wird dort nichts angezeigt.

**Comment by Apollon77** [comment]
fixed on Github
