### ISSUE TITLE
Folder is gone after renaming it

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.scenes#104]
Admin 4.2.1
Scene Adapter 2.3.6

Folder is not visible any more after editing the name of the folder

Steps to reproduce
- Create a folder "test"
- Edit foldername from "test" to "test1"
- Folder is not visible any more -> not ok

**Comment by Feuer-sturm** [comment]
Problem still exists with Admin v5.1.25 and Scene Adapter 2.3.6

**Comment by GermanBluefox** [comment]
Is it happens only with empty folders?

**Comment by Feuer-sturm** [comment]
@GermanBluefox Yes, this happens only with empty folders.

**Comment by Feuer-sturm** [comment]
Open

**Comment by reutli** [comment]
should not be closed, as it's a bug

**Comment by GermanBluefox** [comment]
If the folder is empty it will not be saved anyway

**Comment by Feuer-sturm** [comment]
Issue is fixed with v2.4.2
Thanks.
