### ISSUE TITLE
Variable Delay Zeit

### ISSUE THREAD

**Issue by pdmetze** [ioBroker/ioBroker.scenes#112]
Hi! Es wäre klasse, wenn man für jede Aktion eigene Verzögerungszeiten einstellen kann, statt nur eine Verzögerung für alle.

**Comment by GermanBluefox** [comment]
Das sollte doch gehen:
![image](https://user-images.githubusercontent.com/4582016/131561781-040f0247-d9e6-414a-aa8f-348475e4ac2e.png)

**Comment by pdmetze** [comment]
Ups, das hatte ich nicht bemerkt, sorry. Dann schließe ich das hier mal... Danke!
