### ISSUE TITLE
Problem with status 'unvcertain" and JS-Controller >= 3.3

### ISSUE THREAD

**Issue by Wildbill-Z** [ioBroker/ioBroker.scenes#121]
I have two scenes which have several lights in common. If all lights are off, all is OK and both scenes become false. But if I start one scene, the other one becomes 'uncertain' (expected behaviour, only one can be true).
Since JS-Controller 3.3 I get this in the log:
`State value to set for "scene.Wohnzimmerlicht" has to be type "boolean" but received type "string" `
and otherwise if I start the other scene.
Datapoint in iobroker objects is type boolean and only expects true or false but gets string 'uncertain' in this moments.

Greetings, Jürgen

**Comment by Apollon77** [comment]
@GermanBluefox hm ... Should we declare all scenes objects as "mixed" or change from "uncertain" to null if value is not nown (which would be a bigger bresking change)

**Comment by Wildbill-Z** [comment]
I forgot to say: Manual changing type of objects from 'boolean' to 'mixed' ('gemischt' in german) seems to fix the problem. No more warnings in log and all seems to work as expected.
Greetings, Jürgen

**Comment by GermanBluefox** [comment]
Please try 2.3.7

**Comment by Wildbill-Z** [comment]
I updated to 2.3.8 which was the actual one in npm. No problem so far. But as I already set all objects to 'mixed' the were no problems at all before.
I'll close this issue and say Thank you.
Greetings, Jürgen
