### ISSUE TITLE
Loosing reference to scene by moving to a folder

### ISSUE THREAD

**Issue by reutli** [ioBroker/ioBroker.scenes#172]
After BUG in #159 is fixed following should be fixed:

If you're pulling a scene from root in a folder all references to this scene are lost in all scripts/Blockly's.

I'd assume that structural changes to a scene should not lead into a complete necessity to overwork als scripts. Scenes should be used by a (their) unique ID, no matter where they are (newly) structured/shifted to.

**Comment by jbubik** [comment]
Hi @reutli , every scene is an Object in ioBroker. Every Object is referenced by its textual identifier (eg. scene.0.myfolder.myscene). Every Adapter stores references to Objects in this form and the configuration is saved differently in each Adapter.

**I'm afraid you are asking too much with this requirement.** To switch all references in all Adapters to numeric IDs is too much work for all developers of all Adapters. To fix an old textual reference to a new one by ioBroker.scenes would require to write code that modifies configurations of the other ioBroker Adapters. Unless you are volunteering to spend your lifetime maintaining such code yourself, I don't see any way forward.

**Please plan your Scenes properly at the start of your deployment.** And yes, I did found this principle the hard way too. I had to fix references to all my scenes once I decided to split them from root to folders. I had to do it in ioBroker.javascript, ioBroker.vis, ioBroker.flot and in scenes referencing other scenes.

A section in the README.md on Folders explaining the principles would be very valuable for new users.

**Comment by p33k** [comment]
> After BUG in #159 is fixed

did I miss something? when was it fixed how? still persists in my installation

**Comment by reutli** [comment]
> > After BUG in #159 is fixed
> 
> did I miss something? when was it fixed how? still persists in my installation

unfortunately it was not yet fixed. I wanted to state, that it would be great to fix this issue after the bug #159 would have been fixed ...

**Comment by reutli** [comment]
This should be NOT stale, because strongly needed!

**Comment by reutli** [comment]
Will the adapter be updated any more? It is great solution to add scenes to iobroker, but since there are many issues open (partly with same issue) for a long time it seems development is dead for now.
It would be great to get an information regarding the situation. For now version 2.3.3 seems the last (not latest) version which is stable for using. This is always a problem to keep in mind for all iob users to keep in mind, not to update this adapter to the latest stable version!

Please add some information for the users what's about getting rid of the issues.

THX
best
Michael

**Comment by GermanBluefox** [comment]
@reutli I cannot do that. According to your request, I should change all adapters (vis, javascript, node-red, ...) if the path to scene was changed. It is imposible.

**Comment by Apollon77** [comment]
That’s valid. Then I would propose a warn message that informs the user that „object ids change and so all uses needs to be adjusted.  You really want to do it?“ - what about that for transparency?

**Comment by GermanBluefox** [comment]
I added warning if the scene moved.

**Comment by Apollon77** [comment]
Thank you very much!
