### ISSUE TITLE
Scenes don't stay active if set-point has different read-data point

### ISSUE THREAD

**Issue by quotschmacher** [ioBroker/ioBroker.scenes#174]
**Describe the bug**  
i'm moving to zigbee2mqtt and so the set-point has a different id than the read-point. so i create a alias combining both and use this alias in my scene. but using this, the selected scene won't stay active. if i use only the set datapoint it works.

**To Reproduce**  
use a alias that has different read and write ids
![image](https://user-images.githubusercontent.com/50583947/192120577-4f6857ec-efc6-45aa-b0c1-93039601ea6b.png)

**Expected behavior**  
the selected scene should have a `true` value 

**Versions:**  
 - v2.3.9
 - v6.0.3
 - docker container

**Additional context**  
in this screenshot "licht1" was set to true but then it resetted to false.

![image](https://user-images.githubusercontent.com/50583947/192120555-8c046601-44ab-47aa-b401-d0cb1dcdb3c3.png)

**Comment by Apollon77** [comment]
Can you please nalso show the elevant matching "original values" pf read and write states? Scene donot know about alias specialities, so it does "read state" and react based on this value ...
YOu can also enablce scene debug log and post this and tell exactly which IDs are the relevnt ones

**Comment by quotschmacher** [comment]
![image](https://user-images.githubusercontent.com/50583947/192120914-a5587ede-19fd-46a2-8e9d-7c33493b4694.png)

the write datapoint
```
{
  "_id": "mqtt.0.zigbee2mqtt.wohnzimmer.licht.essbereich.set.brightness",
  "common": {
    "name": "zigbee2mqtt/wohnzimmer/licht/essbereich/set/brightness",
    "write": true,
    "read": true,
    "role": "variable",
    "desc": "mqtt client variable",
    "type": "number",
    "min": 0,
    "max": 254
  },
  "native": {
    "topic": "zigbee2mqtt/wohnzimmer/licht/essbereich/set/brightness"
  },
  "type": "state",
  "from": "system.adapter.mqtt.0",
  "user": "system.user.admin",
  "ts": 1663797388928,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "min": 0,
  "max": 254
}
```

and the read id
```
{
  "_id": "mqtt.0.zigbee2mqtt.wohnzimmer.licht.essbereich.brightness",
  "common": {
    "name": "zigbee2mqtt/wohnzimmer/licht/essbereich/brightness",
    "write": true,
    "read": true,
    "role": "variable",
    "desc": "mqtt client variable",
    "type": "number"
  },
  "native": {
    "topic": "zigbee2mqtt/wohnzimmer/licht/essbereich/brightness"
  },
  "type": "state",
  "from": "system.adapter.mqtt.0",
  "user": "system.user.admin",
  "ts": 1663797388928,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
```

even though scene dows not know about alias, i think it should be possible to use alias datapoints without any restrictions. of course i could simply use the set point in the scene...

**Comment by Apollon77** [comment]
Please add a debug log

**Comment by quotschmacher** [comment]
wanted to get the debug output yesterday so i switched my scene back to the alias: everything is running like i would expect it. no more change in the scene's state to false. i will watch how it behaves in the future and report if there is something weird again. 
so far: sorry for bothering...
