### ISSUE TITLE
permissionError

### ISSUE THREAD

**Issue by Tomek5111** [ioBroker/ioBroker.scenes#177]
Hallo
Wenn ich eine szene abspeichern oder löschen möchte kommt leider immer der fehler : permissionError

**Comment by Apollon77** [comment]
Bitte mal Admin 6.2.2.3 versuchen

**Comment by Tomek5111** [comment]
> Bitte mal Admin 6.2.2.3 versuchen

Ich habe Admin 6.2.22 installiert und das soll das neuste sein jedenfalls finde ich kein 6.2.23..

**Comment by Apollon77** [comment]
6.2.23 is beta ... will come to stable soon

**Comment by Tomek5111** [comment]
> 6.2.23 is beta ... will come to stable soon

Ok thank you
