### ISSUE TITLE
Szenen Status hängt auf True

### ISSUE THREAD

**Issue by xmace** [ioBroker/ioBroker.scenes#18]
Hi, 
habe leider in letzter Zeit häufiger das Problem, dass der Status einer Szene auf True hängen bleibt und nicht mehr ausgeführt werden kann.

Ich triggere auf "Button pushed" und steuere dann die Szenen auf "true" um z.b. die Rollläden zu öffnen oder schließen. Normalerweise ändert sich der status der Szene dann auf false wenn einer der Werte abweicht.

Mache ich irgendwas falsch? Auch Adapter neu starten hilft meist nicht. Nur ein Reboot des iobrokers.

LG, xmace
![scene](https://user-images.githubusercontent.com/15639172/35144801-ef8cf3da-fd05-11e7-9129-ee3066d87ad0.PNG)

**Comment by ZZMajor** [comment]
Ich hänge mich mal mit an, da ich das gleiche Problem habe. Wenn Szenen direkt unter den Szenen geschaltet werden, dann aktualisiert sicvh auch der Status. Wenn Szenen aber z.B. von einem Skript geschaltet werden (über Trigger oder auch direkt in den Objekten), dann ändert sich der Status unter Objekte nicht. Auch im Szenen-Adapter selbst stimmt der Status true/false dann nicht unbedingt mit den wahren Gegebenheiten.
Die Szenen selbst werden aber, zumindest bisher, einwandfei ausgeführt, nur der Status wird falsch angezeigt.
Gefühlt könnte das seit Umstellung auf Admin 3 sein.
Ist das nur bei mir so?

Gruß, Jürgen

**Comment by GermanBluefox** [comment]
Bleibt der Status auch nach F5 im Browser falsch?

пн, 27 авг. 2018 г., 17:56 ZZMajor <notifications@github.com>:

**Comment by ZZMajor** [comment]
Ja, auch Neuladen mit F5 oder dem Aktualisierungsbutton ändert da nichts. Ich habe noch ein wenig rumgespielt und konnte es etwas eingrenzen:
Wenn ich im Szenen-Adapter Szenen manuell starte oder stoppe, so wird die Szene ausgeführt bzw angehalten und auch der Status der Szene unter Objekte wird korrekt angezeigt.
Wenn ich eine Szene aus einem Skript oder manuell in den Objekten starte oder stoppe, so wird die Funktion ebenfalls korrekt ausgeführt, aber der Status der Szene bei den Objekten und auch im Szenenadapter bleibt einfach mit dem alten Wert stehen. Dabei spielt es keine Rolle, ob ich die Szene direkt bediene oder das über einen Trigger passiert. Die Zustände der eigentlichen Geräte wird dann im Szenenadapter aktualisiert und korrekt angezeigt, nur die Szene selbst wird vom Status her nicht aktualisiert.
Es scheint sich im Übrigen auch nur um ein Darstellungsproblem zu handeln, was mir aber jetzt erst auffiel. Ich habe zwei Szenen, die sich gegenseitig ausschließen (wenn ich die eine laufen habe und starte die andere soll die eine ausgehen, es erfolgt also eine Abfrage auf den Objekt-Datenpunkt XXX.scene true/false) und das Skript erhlt komischerweise den korrekten Zustand. Also auch wenn mir in den Objekten false angezeigt wird, obwohl die Szene eigentlich läuft, bekommt das andere Skript den korrekten Zustand übermittelt.

Ich habe den Effekt auf verschiedenen Rechnern sowohl mit Windows als auch Linux und sowohl mit Firefox, Edge und Chromium, so dass ich einen Fehler dahin eher ausschließen würde. Wie schon gesagt, könnte der Effekt seit Admin3 aufgetreten sein, da es früher immer korrekt anzeigte.

Gruss, Jürgen

**Comment by Seraphis411** [comment]
Problem besteht immer noch und auch bei mir in genau der Form wie bei ZZMajor, also so gesehen nur optisch.

Ergänzende Beobachtung:
Wenn eine Szene erstmal auf True hängt (inkl. falscher/fiktiver Status-Werte der Geräte) hilft es nichtmal, wenn die gleichen Geräte von einer anderen Szene gesteuert werden. Stattdessen muss die hängende Szene manuell über den Adapter nochmal aufgerufen werden und erst wenn dann danach der Status der Geräte geändert wird, schaltet die zuvor hängende Szene korrekt auf False.

**Comment by terne81** [comment]
Ich kann das Problem vielleicht weiter eingrenzen:
unter Objekte wird der richtige Status angezeigt - jedoch im Scene-Adapter unter der Konfiguration
" Auswahl des Triggers " stimmt der Status nicht. Und ändert sich auch nicht.

![1](https://user-images.githubusercontent.com/34346940/50895317-0fdcd200-1406-11e9-9ea8-26d8eaaba3a6.png)


Gruß Thorsten
