### ISSUE TITLE
Wunsch: Auch in den Elemente die Möglichkeit der Beschreibung

### ISSUE THREAD

**Issue by ruhr70** [ioBroker/ioBroker.scenes#2]
Es gibt ein Beschreibungsfeld für die Szene. 

Der Wunsch wäre , dies auch für die einzelnen Elemente innerhalb einer Szene nutzen zu können. In der Tabellenübersicht sind die Beschreibungsfelder der Elemente leer, da dort keine Beschreibung möglich ist.

Gerade beim Einsatz von hue würde sich eine Beshcreibung manchmal anbieten.

**Comment by GermanBluefox** [comment]
https://github.com/ioBroker/ioBroker.scenes/commit/63042511012c42cc20cb6676626ce5f07b96ceba

**Comment by GermanBluefox** [comment]
Implemented in 2.0.0
