### ISSUE TITLE
scenes.0 wird nicht erzeugt

### ISSUE THREAD

**Issue by ruhr70** [ioBroker/ioBroker.scenes#24]
node.js 8, npm 5
scenen Adapter 1.0.2

Erste Szene angelegt. Der Adapter legt keinen Objektbaum (scenes.0) an.
system.adapter.scenes.0 ist vorhanden.

Adapter gelöscht und neu hinzugefügt.

Die vorher eingerichtete Szene war dann wieder vorhanden.
Der Objektbaum fehlt weiterhin.

**Comment by Apollon77** [comment]
Im Admin unter "Objekte" mal "reload" (Icon mit den zwei Pfeilen) geklickt?

**Comment by ruhr70** [comment]
ja. Auch zwischenzeitlich einen anderen Browser geöffnet.

**Comment by ruhr70** [comment]
Wenn man den Adapter löscht steht im Admin unter Adapter:
Keine Zahl bei Anzahl, installiert: 1.0.2, verfügbar 1.0.2

Wenn man eine Instanz hinzufügt geht die Installation "blitzschnell".

Im Adapter löschen und dann neu hinzufügen?
Oder ist der Adapter dann im Admin im Repro weg?

Scheint auch kein Adapter Problem zu sein, da ich das gleiche Problem auch beim Unifi Adapter habe.

**Comment by guergen1** [comment]
Scene.0 wird bei mir zwar angelegt, wenn ich allerdings eine Scene hinzufüge nach folgendem Muster:
![grafik](https://user-images.githubusercontent.com/34395245/66226887-2c2f4600-e6dc-11e9-8c18-2293c5852029.png)
wird diese nicht unter scene.0 sondern unten separat abgelegt, mehrere Browser probiert, Cache leer...
![grafik](https://user-images.githubusercontent.com/34395245/66226981-68fb3d00-e6dc-11e9-89b0-eb5418129927.png)
Wenn ich eine Scene nur anlege, ohne sie zu benennen und unter Objekten den Namen ändere, dann ist sie an der richtigen stelle.
Soll das so sein?

**Comment by guergen1** [comment]
Ahhh... im Namen muss vorne die Instanz-Neummer )0.) eingegeben werden, dann geht es!

**Comment by GermanBluefox** [comment]
Implemented in 2.0.0
