### ISSUE TITLE
Sollwert für Status Wahr / Sollwert für Status falsch

### ISSUE THREAD

**Issue by smartboart** [ioBroker/ioBroker.scenes#25]
Hallo, beim Setzen der Sollwerte stimmt die Bezeichnung nicht. es steht überall Sollwert für Status wahr...
Und der Reiter zum Öffnen des untersten Sollwert für Status Falsch ist ohne Funktion.
Ebenfalls kann keine Bedingung für Falsch eingetragen werden. Egal was vorgewählt ist, es wird immer alles eingeschaltet... 
![unbenannt](https://user-images.githubusercontent.com/38385805/41206169-584b49d4-6d00-11e8-9b2c-5ba4f904f446.PNG)

**Comment by ToTXR4Y** [comment]
Gibt es hier schon Neuerungen?

**Comment by DocYester** [comment]
und der soll-wert false bei falsch funktioniert nicht - state bleibt true

**Comment by Boris-Scharinger** [comment]
Habe das selbe Problem - kann jemand die UI korrigieren?

**Comment by GermanBluefox** [comment]
Implemented in 2.0.0
