### ISSUE TITLE
Different paths for adapter and instance

### ISSUE THREAD

**Issue by DEV2DEV-DE** [ioBroker/ioBroker.scenes#280]
There are two different paths for the states of the adapter and the ones for the instances.
Is this an error or desired in this way?

![image](https://github.com/ioBroker/ioBroker.scenes/assets/95883579/dee8c3a9-446d-4645-964c-c40c9e4f4f2e)

**Comment by GermanBluefox** [comment]
No. It is not an error. All scenes of all instances are stored in 'scene.0'. Historical issue.
