### ISSUE TITLE
Szene soll wahr bleiben

### ISSUE THREAD

**Issue by Elexil** [ioBroker/ioBroker.scenes#30]
Hallo,

ich fände es hilfreich, wenn Szenen auf dem Status wahr bleiben würden, solange nicht alle Geräte in der Szene auf false stehen. Somit kann ich Beispielsweise eine Lichtsteuerung "Alles" für einen Raum auch sinnvoll verwenden.

Aktuell stellt sich meine Szene immer auf undefined, und wenn ich diese nochmals aufrufe, gehen alle Lichter an, auch die die schon aus sind, bevor ich dann alle ausschalten kann. Dummerweise hängen da auch die Kinderzimmer dran. Kommt nicht so toll, Abends erstmal alles zu beleuchten :)

Gruß
Elexil

**Comment by Apollon77** [comment]
Was meinst du mit „nochmals alle Aufrufe“? Du musst schon den gewünschten wert (true/false = an/aus) setzen. Wenn du auf false setzt geht alles aus und nicht erstmal an.

**Comment by Elexil** [comment]
Ich habe eine Szene "Alles", da hängen alle Lampen der Wohnung drin.

Solange alle Lampen gleichzeitig an sind, ist auch der Status der Szene wahr. Schalte ich nun einzelne Lampen aus (soll vorkommen, man kann nicht überall sein :) ) geht der Status der Szene auf undefined.

Wenn ich nun alle Lampen ausschalten möchte und die Szene "Alles" triggere (Button in VIS) setzt er erst einmal alles auf wahr, heißt mitten in der Nacht habe ich hier ein Sonnenstudio, bevor ich es im zweiten Schritt dann ausschalten kann.

**Comment by Apollon77** [comment]
Das undefined ist Absicht weil der Zustand ja gemischt ist. Es sind nicht alle an. 

Das alles auf true geht liegt wohl daran das die vis Schalter bei undefined hier „aus“
Als Status annehmen ... hm ..,

**Comment by xmace** [comment]
Hatte das selbe problem. Habs dadurch gelöst, dass der Schalter in VIS immer auf false setzt und alles ausschaltet.

Alternativ versuch mal nicht nur die Bedingungen für true im szenen adapter anzugeben sondern auch für false (bei dimmern auf 0/false) achten. Seitdem gibts bei mir auch kein undefined mehr.

Lg

**Comment by Elexil** [comment]
Hallo xmace,

ich benutze die Metro Tiles für die Licht anzeige:
![image](https://user-images.githubusercontent.com/37534416/50592119-05b15580-0e93-11e9-86e6-247a0ef55e52.png)

Sobald ich ein Licht anschalte, geht der Szenen Status auf undefined und das Tile verfärbt sich gelb, wie man sehen kann. Wenn ich nun aber den den Alles Knopf drücke, wird die Szene erst einmal auf wahr gesetzt komplett. 

Ich habe bisher nicht gefunden, wie ich dem Tile da einen Wert mitgeben kann. Ich würde es jetzt vermutlich mit nem Skript versuchen, das mir dann die Szene auf falsch setzt. Aber nichts desto trotz, macht ein Status undefined keinen Sinn, entweder an oder aus. Und solange etwas in der Szene auf wahr steht, sollte die gesamt Szene auf wahr sein.
