### ISSUE TITLE
Enable/Disable scene states via datapoint or message

### ISSUE THREAD

**Issue by steefan85** [ioBroker/ioBroker.scenes#310]
**Is your feature request related to a problem? Please describe.**

I'd like to enable/disable states which are used within a scene depending on sveral external conditions (e. g. depending on "auto-mode" on/off or lights which shall be temporary stay off).

It is possible to manually disable states, but they can't be accessed via DP.

**Describe the solution you'd like**
Create DPs (or message) to control whether specific state is enabled/disabled in the scene.
(Similar option for the whole scene is available via message.)

**Describe alternatives you've considered**
I could use scripts, but the option to exclude specific states would make things much easier and there would be other use cases, too.

**Additional context**
![image](https://github.com/ioBroker/ioBroker.scenes/assets/24730529/6a18b136-a6b9-4094-ab8a-4c5a1cb709e3)

**Comment by GermanBluefox** [comment]
You can create different scenes. But generally the request is too specific. It will generate a lot of datapoints for every scene member.
Otherwise, you can directly manipulate the scenes object via script.
