### ISSUE TITLE
Variable output

### ISSUE THREAD

**Issue by t1m02k16** [ioBroker/ioBroker.scenes#33]
![whatsapp image 2019-02-22 at 21 40 22](https://user-images.githubusercontent.com/19432480/53448907-d8a79c00-3a18-11e9-840a-c3fa34acb9e5.jpeg)

Ich frage hier den Zustand meiner Fenster ab. Leider kommt es sehr häuftig vor, dass der Zustand nicht geändert bzw. aktualisiert wird. Siehe Upload
It happens very often that the variable output is wrong

**Comment by xmace** [comment]
what is your expectation?

in the given example the value of the scene should be "undefiniert" because it's not true (not all 100) and not false (not all 0)

**Comment by t1m02k16** [comment]
uncertain

**Comment by GermanBluefox** [comment]
Please test with 2.0.0 and reopen if the error still exists
