### ISSUE TITLE
[enhancement] don't update states if already set properly

### ISSUE THREAD

**Issue by xmace** [ioBroker/ioBroker.scenes#35]
Hi,

currently all added object states are set to specified true/false value even if they are have already the specified value.

for example:
"turn all off scene"
-> all added objects are set to false even if they are already switched off. 
Causing massive time delay and (maybe?) not necessary duty cycle for homematic components.

proposal:
skip all objects which have the proper state already set. 
Like "change value only if current value not as specified"

improvement:
less duty cycle and much faster processed scene.

Thanks

**Comment by xmace** [comment]
Hi guys,

any updates on this?

With my basic programming skills I assume it's not a big deal to implement this feature, or?

I would like to do it by my own if someone could lead me the direction ^^

best regards,
xmace

**Comment by GermanBluefox** [comment]
Will be implemented in 2.0.1
