### ISSUE TITLE
Angabe von Toleranzen wären sehr hilfreich

### ISSUE THREAD

**Issue by JilliOe** [ioBroker/ioBroker.scenes#38]
Hallo zusammen,
es wäre sehr hilfreich, wenn man zu den Sollwerten auch Toleranzen angeben könnte, innerhalb derer ein Wert als wahr angenommen wird:
((SOLL-Toleranz) <= IST <= (SOLL+Toleranz)) ? wahr : falsch
Das wäre enorm praktisch, da bei Jalousien oft nicht exakt der Wert zurückgemeldet wird, der eingestellt werden soll. Bei Abweichungen von 1% oder 2% darf die Szene durchaus noch als wahr angenommen werden.
Vielen Dank und viele Grüße

**Comment by GermanBluefox** [comment]
Implemented in 2.0.5

**Comment by JilliOe** [comment]
Läuft super!

 

 

-- 
Kilian Eisenhauer
Martin-Luther-Str. 5
D-64347 Griesheim
+49 (0) 178 / 132 69 53
 <mailto:kilian.e@gmx.de> kilian.e@gmx.de

 

Von: Bluefox <notifications@github.com> 
Gesendet: Sonntag, 14. Juni 2020 20:27
An: ioBroker/ioBroker.scenes <ioBroker.scenes@noreply.github.com>
Cc: JilliOe <kilian.e@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [ioBroker/ioBroker.scenes] Angabe von Toleranzen wären sehr hilfreich (#38)

 

Implemented in 2.0.5
