### ISSUE TITLE
Create scenes from other adapter

### ISSUE THREAD

**Issue by kosimst** [ioBroker/ioBroker.scenes#40]
The docs do not mention anything about any kind of exposed API in order to access the adapter's features from elsewhere. I would like to create a scene/group programmatically from another ioBroker adapter. Is this possible? Or if it is not intended to do so, where can I find the part of the code that is responsible for creating new scenes?

**Comment by GermanBluefox** [comment]
Yes it is possible, but tricky. Here you can find the structure of scene:
https://github.com/ioBroker/ioBroker.scenes/blob/master/main.js#L4

You just should write an object a `scene.0.sceneName` with the above described object.
