### ISSUE TITLE
New UI has unreadable content

### ISSUE THREAD

**Issue by agross** [ioBroker/ioBroker.scenes#44]
After reporting #43 I tried accessing ioBroker directly without the proxy in place. While the scene editor loads, some of its content is unreadable (white text on grayish background).

![image](https://user-images.githubusercontent.com/16245/84606429-6c1f0d80-aea6-11ea-9e8b-d2f99c1da1ad.png)

**Comment by hawi1981** [comment]
I have the same problem when I try to open the web interface on my Mac (no matter which browser). When I use my other Windows computer, everything works and it looks normal.

**Comment by cyberax17** [comment]
Is it possible to switch back to the old interface ? To me this was more clear with better overview and quite intuitive. I liked the table view.

**Comment by agross** [comment]
@cyberax17 I reinstalled 1.x by using this URL in the "Install from GitHub / Custom" dialog: `https://github.com/ioBroker/ioBroker.scenes/tarball/e7e45ce4726612157551fecb1502287572fdfc24`

**Comment by GermanBluefox** [comment]
Fixed in 2.0.9

**Comment by cyberax17** [comment]
Super, danke jetzt ist es wenigstens wieder lesbar! 
Doch würde ich gerne Dir Rückkehr/ Option der Tabellenansicht begrüßen ;-)

**Comment by Apollon77** [comment]
Denke das wäre dann ein eigenes issue

**Comment by Steiger04** [comment]
Danke für die schnelle Umsetzung! Mir persönlich gefällt das neue Bedienkonzept sehr gut. Man muss sich erst gewöhnen, wenn man aber ein paar Szenen angelegt hat, klappt es wunderbar.
