### ISSUE TITLE
continuously editor loading

### ISSUE THREAD

**Issue by 603games** [ioBroker/ioBroker.scenes#45]
hey, 
since upgrading from 1.1.0 to 2.0.6 the scene editor loads continuously but does not start anymore.

Regards 
Andreas

**Comment by Marsx79** [comment]
The same problem here. 

Regards 
Marcel

**Comment by pfleiderer** [comment]
Same here
greetings
Hans-Peter

**Comment by kotbox** [comment]
Same here !

Regards
Stefan

**Comment by elo79** [comment]
Same here, it seems that the adapter doesn´t work at all at the moment

**Comment by Anzic23** [comment]
+1

**Comment by daneb255** [comment]
+1

**Comment by Black-Thunder** [comment]
Facing the same issue. Following error occurs in the developer console:

![Capture](https://user-images.githubusercontent.com/972581/84663662-c313f980-af1d-11ea-9935-8e6f7ae4a55c.PNG)

```
Uncaught (in promise) SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at App.js:370

(anonymous) @ App.js:370
Promise.then (async)
refreshData @ App.js:346
(anonymous) @ App.js:259
dc @ react-dom.production.min.js:131
no @ react-dom.production.min.js:212
hl @ react-dom.production.min.js:255
e.unstable_runWithPriority @ scheduler.production.min.js:19
In @ react-dom.production.min.js:122
vl @ react-dom.production.min.js:248
Xo @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
e.unstable_runWithPriority @ scheduler.production.min.js:19
In @ react-dom.production.min.js:122
qn @ react-dom.production.min.js:123
Gn @ react-dom.production.min.js:122
Zo @ react-dom.production.min.js:230
enqueueSetState @ react-dom.production.min.js:132
y.setState @ react.production.min.js:12
(anonymous) @ App.js:258
Promise.then (async)
(anonymous) @ App.js:256
Promise.then (async)
onConnectionReady @ App.js:252
[..........]
```

**Comment by agross** [comment]
Appears to happen due to nonstandard port configuration, see #43

**Comment by Black-Thunder** [comment]
With v2.0.7 (installed from GitHub) the editor now loads at least , but the UI elements are invisible: 

![Capture](https://user-images.githubusercontent.com/972581/84708345-9f25d780-af60-11ea-8965-9f227f5eae90.PNG)

Probably now related to https://github.com/ioBroker/ioBroker.scenes/issues/44

**Comment by GermanBluefox** [comment]
Duplicate to https://github.com/ioBroker/ioBroker.scenes/issues/44
