### ISSUE TITLE
Scanes did't save

### ISSUE THREAD

**Issue by Anzic23** [ioBroker/ioBroker.scenes#46]
created a new scene. I click the save button and the scene disappears.

---

**System data:**

Platform: linux
Distribution: Debian GNU/Linux
Architecture: x64
Model: Intel(R) Celeron(R) CPU G1610T @ 2.30GHz
RAM: 9.73 GB
Node.js: v10.21.0
NPM: 6.14.4
Model: ARMv7 Processor rev 4 (v7l)
RAM: 975.6 MB
Node.js: v12.18.0
NPM: 6.14.5
JS-Controller (1): 3.1.5
Admin: 4.1.1
Scenes: 2.0.6

> *created by ioBroker.info*

**Comment by algar42** [comment]
Confirm. New UI does not save newly created scenes (v2.0.7)
I got the following in the log:

scenes.0 | 2020-06-16 09:55:19.209 | info | (2009) restartAdapter
-- | -- | -- | --
admin.0 | 2020-06-16 09:55:19.205 | warn | (23367) This object will not be created in future versions. Please report this to the developer.
admin.0 | 2020-06-16 09:55:19.203 | warn | (23367) Object scene.0.Освещение.scene0 is invalid: obj.type has an invalid value (scene) but has to be one of state, channel, device, enum, host, adapter, instance, meta, config, script, user, group

**Comment by GermanBluefox** [comment]
Fixed in 2.0.8

**Comment by Karatekid2407** [comment]
tested with v2.0.9 and is fixed. Can be closed.
