### ISSUE TITLE
Nach Update wird nur noch es wurden noch keine Szenen erstellt angezeigt!!!!

### ISSUE THREAD

**Issue by PommesTC** [ioBroker/ioBroker.scenes#47]
Und alle meine erstellten Szenen sind weg!

---

**System data:**

Model: Common KVM processor
RAM: 2.94 GB
Node.js: v12.18.0
NPM: 6.14.4
Platform: linux
Distribution: Debian GNU/Linux
Architecture: x64
JS-Controller (1): 3.1.5
Admin: 4.1.1
Scenes: 2.0.7

> *created by ioBroker.info*

**Comment by GermanBluefox** [comment]
Screenshot? Druck mal Strg+A. Kann man mehr sehen?
Wieso so viele Ausrufezeichen?????

**Comment by ThorstenBoettler** [comment]
Bei mir das gleiche Problem

Es wird eine leere Seite angezeigt. Dort steht nur:
Es wurden noch keine Szenen erstellt


Betriebssystem: linux
Architektur: arm
CPUs: 4
Geschwindigkeit: 1500 MHz
Modell: ARMv7 Processor rev 3 (v7l)
RAM: 3.81 GB
Node.js: v12.18.0
NPM: 6.14.4

**Comment by backons** [comment]
Bei mir das selbe Problem ! Alle Scenen sind weg und ich wüsste auch nicht wie ich eine neue nun anlegen soll...

**Comment by roadie33** [comment]
Bei mir werden die Szenen auf http://iobroker:8081/#tab-scenes auch nicht angezeigt. Sie sind aber noch vorhanden und funktionieren teilweise. Gefunden habe ich die Szenen auf http://iobroker:8081/#tab-objects. Alle Szenen, die ich angelegt habe sind dort aufgelistet (z.B. scene.TV)

**Comment by OstfrieseUnterwegs** [comment]
Meine angelegten Scenes wurden angezeigt, aber nachdem ich zu einer Scene ein Objekt zugefügt und gespeichert habe, was diese Scene nicht mehr sichtbar. Die anderen sind noch da. Die verlorene Scene ist nach wie vor in den Objekten vorhanden.

**Comment by GermanBluefox** [comment]
Die Szenen sind immer noch da. Man muss (unter 2.0.9) die als Object im admin aufmachen und `"type": "scene"` auf `"type": "state"` manuell ändern. Dann tauchen die Szenen wieder auf.

In der 2.0.9 ist der Fehler gefixt.

**Comment by backons** [comment]
Habe das Update installiert. Nun kommen die Szenen unter dem Adapter wieder. Den type musste nicht ändern der stand schon automatisch auf State. Bei Rolle steht scene.state.
Wenn ich allerdings auf Objekte gehe und dort dann den State ändern möchte auf true/false oder 0/1 kann ich dort keinerlei Änderung machen. Ich kann ihn also nicht steuern...

**Comment by backons** [comment]
auch aufgefallen ist mir das wenn eine neue Scene anlege dann wird dieser Datenpunkt im Ordner scene.0 angelegt. Die vorhandenen Szenen sind aber nach wie vor in der Hauptebene unter den Ordnern. Die neu erstellte Scene kann ich leider auch nicht steuern.

**Comment by cyberax17** [comment]
Bei mir auch komisches Verhalten: die Szenen sind zwar da, es werden aber nicht alle Schritte ausgeführt, bzw. nicht korrekt. Manchmal zB wird ein Objekt auf 1 und manchmal auf True gesetzt. Wenn ich die Objekte manuell steuere funktioniert alles, über den Szenen Adapter funktioniert es leider nicht so zuverlässig. Manchmal ja, manchmal nein. Irgend ein Bug?

**Comment by GermanBluefox** [comment]
> Bei mir auch komisches Verhalten: die Szenen sind zwar da, es werden aber nicht alle Schritte ausgeführt, bzw. nicht korrekt. Manchmal zB wird ein Objekt auf 1 und manchmal auf True gesetzt. Wenn ich die Objekte manuell steuere funktioniert alles, über den Szenen Adapter funktioniert es leider nicht so zuverlässig. Manchmal ja, manchmal nein. Irgend ein Bug?
> 
> Anmerkung: mit der alten Interface-Version hat es einwandfrei funktioniert.

Am Backend hat sich kaum was geändert, außer, dass jetzt Toleranz eingegeben werden kann.
Kannst du deutlicher den Fehler formulieren, so dass ich den reproduzieren kann?

**Comment by GermanBluefox** [comment]
> Manchmal zB wird ein Objekt auf 1 und manchmal auf True gesetzt.

Das kann nicht sein. 1 kann stehen, wenn man z.B. KNX verwendet und knx dummerweise quittiert das Kommando mit "1" und nicht mit "true"

**Comment by GermanBluefox** [comment]
> auch aufgefallen ist mir das wenn eine neue Scene anlege dann wird dieser Datenpunkt im Ordner scene.0 angelegt. Die vorhandenen Szenen sind aber nach wie vor in der Hauptebene unter den Ordnern. Die neu erstellte Scene kann ich leider auch nicht steuern.

Hast du screenshot für mich?

**Comment by backons** [comment]
> > auch aufgefallen ist mir das wenn eine neue Scene anlege dann wird dieser Datenpunkt im Ordner scene.0 angelegt. Die vorhandenen Szenen sind aber nach wie vor in der Hauptebene unter den Ordnern. Die neu erstellte Scene kann ich leider auch nicht steuern.
> 
> Hast du screenshot für mich?

![Bildschirmfoto 2020-06-20 um 20 45 53](https://user-images.githubusercontent.com/45655418/85209315-2bf0dc80-b337-11ea-91d2-dd77d1cdee1b.png)

**Comment by cyberax17** [comment]
> > Manchmal zB wird ein Objekt auf 1 und manchmal auf True gesetzt.
> 
> Das kann nicht sein. 1 kann stehen, wenn man z.B. KNX verwendet und knx dummerweise quittiert das Kommando mit "1" und nicht mit "true"

In der Tat - ich habe KNX gemixt mit anderen Aktoren, das könnte die True/1 Unterschiede erklären.

**Comment by GermanBluefox** [comment]
> > > auch aufgefallen ist mir das wenn eine neue Scene anlege dann wird dieser Datenpunkt im Ordner scene.0 angelegt. Die vorhandenen Szenen sind aber nach wie vor in der Hauptebene unter den Ordnern. Die neu erstellte Scene kann ich leider auch nicht steuern.
> > 
> > 
> > Hast du screenshot für mich?
> 
> ![Bildschirmfoto 2020-06-20 um 20 45 53](https://user-images.githubusercontent.com/45655418/85209315-2bf0dc80-b337-11ea-91d2-dd77d1cdee1b.png)
> 
> Das ist die neu angelegte Scene zum Test. Brauchst du von den alten Szenen auch einen Screenshot ?

So ist es richtig. Alle Szenen MÜSSEN in scene.0 drin sein. Alles anderes ist fehlerhaft.

**Comment by GermanBluefox** [comment]
> > > Manchmal zB wird ein Objekt auf 1 und manchmal auf True gesetzt.
> > 
> > 
> > Das kann nicht sein. 1 kann stehen, wenn man z.B. KNX verwendet und knx dummerweise quittiert das Kommando mit "1" und nicht mit "true"
> 
> In der Tat - ich habe KNX gemixt mit anderen Aktoren, das könnte die True/1 Unterschiede erklären.

Das Verhalten muss in KNX adapter gefixt werden.
