### ISSUE TITLE
Farben unter Opera werden falsch dargestellt

### ISSUE THREAD

**Issue by Steiger04** [ioBroker/ioBroker.scenes#48]
![image](https://user-images.githubusercontent.com/17086944/84792681-72230480-aff4-11ea-8162-7b0f590f57f5.png)

Tritt auf, wenn im Browser unter Erscheinungsbld "Dunkles Design" aktiviert wurde.

**Comment by GermanBluefox** [comment]
Duplicate to https://github.com/ioBroker/ioBroker.scenes/issues/44
