### ISSUE TITLE
Geräteauswahl zeigt nicht alle Daten an

### ISSUE THREAD

**Issue by OstfrieseUnterwegs** [ioBroker/ioBroker.scenes#49]
Der Dialog zur Auswahl zeigt Raum und Funktion nicht an. Die Filter-Liste ist leer. Rolle funktioniert. Außerdem sind Spaltenüberschriften in englisch, ich würde deutsch erwarten.
Browser Chrome Version 83.0.4103.97
Scenes: 2.0.9

![scene-select](https://user-images.githubusercontent.com/23573740/84892882-a94df000-b09e-11ea-8493-788faa75681e.png)

Im Vergleich das selbe Gerät im Dialog des Devices-Adapters. Auch hier übrigens englische Spaltenüberschrift beim Filter.

![select-devices](https://user-images.githubusercontent.com/23573740/84893314-51fc4f80-b09f-11ea-9ece-f36919076a73.png)

**Comment by daniel-2k** [comment]
Kann ich bestätigen. Die Auswahl eines States ist jetzt schwierig, da die Namen fehlen. Fix wäre gut.

**Comment by OstfrieseUnterwegs** [comment]
Spaltenüberschriften nun in deutsch (vlt war vorher ein Upload nicht erfolgreich). Spalten-Werte fehlen immer noch. Das ist besonders beim Namen lästig, weil man immer ein zweites Fenster bruacht um die ID herauszusinden und dann im Scene Adapter nach der ID zu suchen. 
V 2.0.11

**Comment by GermanBluefox** [comment]
Check 2.0.14

**Comment by daniel-2k** [comment]
Now it looks good

**Comment by OstfrieseUnterwegs** [comment]
Issue fixed, Thanks
