### ISSUE TITLE
Werte werden nicht mehr explizit gesetzt

### ISSUE THREAD

**Issue by vain90** [ioBroker/ioBroker.scenes#50]
Hallo zusammen,

ich habe seit dem Update leider das Problem, dass nicht mehr alle meine Szenen funktionieren.
Nach ein wenig testen glaube ich zu wissen woran es liegt.
Und zwar werden eingestellte Farben nicht explizit noch einmal gesetzt, wenn Sie diesen Wert noch haben.

Beispiel:

Ich habe eine Szene TV-Abend. In dieser wird ein RGB-WW-CW LED-Stripe mit einer Farbe gesetzt. In diesem Fall #FFB400.

Nun habe ich eine zweite Szene Wohnzimmer HCL. Dies schaltet den selben LED-Stripe auf einen, je nach Tageszeit, unterschiedlichen Weißton. Von Warmweiß zu Kaltweiß.
Dabei wird aber ein zweiter Datenpunkt verwendet. Die Farbe des Stripes wird über den Datenpunkt "color" eingestellt und die warmweiß und kaltweiß-Werte werden über den Datenpunkt "colortemp".

Wenn ich nun wieder zurück zur Szene TV-Abend wechseln möchte, dann wird die Farbe nicht korrekt eingestellt. Das liegt nun daran dass er ja nun die Farbe wieder setzen sollte. Der Szenen-Adapter scheint nun aber zu erkennen, dass der Datenpunkt noch genau diesen Wert eingestellt hat und setzt ihn nicht explizit nochmal. Aber genau das benötige ich, denn nur so wechselt mein Stripe von den Warm-Kaltweißtönen auf die RGB-Werte.

Ich könnte da jetzt eine Krücke bauen das vorher immer kurz eine andere Farbe eingestellt wird, aber das ist eigentlich nicht Sinn der Sache und belastet gerade Funkprotokolle wie Zigbee unnötig.

Beste Grüße

**Comment by vain90** [comment]
Ergänzung:
Das Problem tritt auch dann auf, wenn ich 3 von 5 Lampen im Whz mit einer Szene einschalte diese aber mit einer anderen Szene über eine Sammelgruppe alle ausschalte.

Denn dann wird die Lampengruppe für alle Lampen im Whz auf false gesetzt, aber die eigentlichen Lampen bleiben auf True. Nun kann ich mit einer Szene keine Lampen mehr einschalten weil diese ja noch auf True stehen und der Adapter das nicht explizit nochmal überschreibt.

Anderherum übrigens auch. Habe ich einmal alle Lampen über die Gruppe ausgeschaltet, dann bleibt der Datenpunkt auf false. Ein erneutes Ausschalten geht dann nicht weil ja bereits false im Datenpunkt steht.

**Comment by Karatekid2407** [comment]
Selbes Problem bei mir.
Meine Ausschaltszene funktioniert nicht mehr, da der Wert nicht erneut gesetzt wird.

Version 2.0.9

**Comment by vain90** [comment]
Ah, ich sehe gerade. Das ist "kaputt" seit diesem Issue: #35 
Da sich das scheinbar auch gewünscht wird, wäre es natürlich super wenn man das pro Szene oder sogar pro Zustand innerhalb einer Szene entscheiden könnte.

**Comment by Karatekid2407** [comment]
Mein Problem ist z.B. die Steuerung von Tasmota Devices über MQTT.
Da hier der cmnd Befehl nicht geändert wird und ich ihn zum ausschalten immer mit 0 updaten muss um eine neue Nachricht zu senden. Das gleiche ist mit der Farbe.
Ich schalte den RGB Strip ein indem ich eine Farbe eingebe und wenn diese aber schon vorhanden ist, weil sie vorher schon gesetzt war, dann schaltet sich der Strip nicht ein.

Für mich ist das ein Urgent Problem, da bei mir alle Scripts nicht mehr funktionieren.

**Comment by GermanBluefox** [comment]
> Ah, ich sehe gerade. Das ist "kaputt" seit diesem Issue: #35
> Da sich das scheinbar auch gewünscht wird, wäre es natürlich super wenn man das pro Szene oder sogar pro Zustand innerhalb einer Szene entscheiden könnte.

It is not a bug, but the feature. Ich schaue mal, was ich machen kann.

**Comment by Karatekid2407** [comment]
Verhalten über Szenen ist ok. (Button "TRUE TESTEN").

Leider funktioniert das ganze mit den Triggern noch nicht so richtig wie zuvor. :/

Meine Idee: 

- Lichtschalter Doppelpress umschalten der Szene über Javascript Variable
- Halten alles ausschalten

Bei jeder Aktion ob halten oder doppelt kommt ein Fehlereintrag.
Die Aktion halten/alles aus lässt sich weder triggern wenn der Wert 0 noch wenn ich einen anderen Wert z.B. 5 einstelle.


![image](https://user-images.githubusercontent.com/38478308/85208799-85570c80-b333-11ea-9897-d80ec7e4f5f1.png)

![image](https://user-images.githubusercontent.com/38478308/85208809-9011a180-b333-11ea-82a3-188183a13b99.png)

![image](https://user-images.githubusercontent.com/38478308/85208817-9bfd6380-b333-11ea-8348-f7501a0bee1a.png)

**Comment by GermanBluefox** [comment]
Fixed in 2.0.11, but you must save your scene one more time

**Comment by Karatekid2407** [comment]
works can be closed
