### ISSUE TITLE
Setze wenn True / set if true

### ISSUE THREAD

**Issue by vain90** [ioBroker/ioBroker.scenes#51]
Hallo,

ich halte die Auswahl bei booleschen Werte für irritierend.
[ ] Setzen wenn True
Das soll ja bedeuten das der Wert "False" in den Datenpunkt geschrieben wird, wenn die Szene auf "True" geht. Aber wie gesagt, dass ist irgendwie merkwürdig dargestellt. Ich würde mich da über eine klarere Benennung freuen.

**Comment by GermanBluefox** [comment]
Vorschlag?

**Comment by GermanBluefox** [comment]
Check 2.0.14 for new style

**Comment by vain90** [comment]
Sorry das ich mich erst jetzt melde. Ich war am renovieren und Abends dann immer tot ins Bett gefallen.

Ich finde die jetzige Darstellung deutlich einfacher zu verstehen. Vielen Dank!

Eine Anmerkung noch:

1. Wenn alle Zustände innerhalb einer Szene "geschlossen" sind. Also nicht im Bearbeiten-Modus, dann steht unten rechts bei jedem Zustand auch noch "Setzen wenn True:" Dort könnte auch einfach nur "Sollwert:" stehen.

![Bildschirmfoto 2020-06-29 um 08 32 26](https://user-images.githubusercontent.com/11925757/85981097-e641ad00-b9e3-11ea-8dff-dff461ce0be3.jpg)

**Comment by GermanBluefox** [comment]
Wird mit 2.1.2 gefixt.
