### ISSUE TITLE
Kein Leerzeichen oder Unterstriche

### ISSUE THREAD

**Issue by Karatekid2407** [ioBroker/ioBroker.scenes#52]
Der Name der Szene als auch die Beschreibung kann nicht mehr mit Leerzeichen oder Unterstrichen beschrieben werden.

Zudem ändert sich bei mir die ID auch nach Änderung des Namens nicht.
Bleibt auf scene0.

**Comment by GermanBluefox** [comment]
Fixed in 2.0.10

**Comment by Karatekid2407** [comment]
Unterstrich in TreeMenu leider nicht vorhanden.

![image](https://user-images.githubusercontent.com/38478308/85208619-2c3aa900-b332-11ea-8fd8-43e1833a1686.png)

**Comment by GermanBluefox** [comment]
It is desired behavior.
