### ISSUE TITLE
Umbenennen von Ordnern nicht möglich

### ISSUE THREAD

**Issue by Karatekid2407** [ioBroker/ioBroker.scenes#53]
Das Umbenennen von Ordnern ist nicht möglich.

Version 2.0.9

**Comment by Karatekid2407** [comment]
Das Umbenennen, hat nach Update auf 2.0.10 einmalig funktioniert.
Danach leider nicht mehr.

**Comment by GermanBluefox** [comment]
Fixed in 2.0.11
