### ISSUE TITLE
[enhancement] Treeview mit subfoldern für Szenen

### ISSUE THREAD

**Issue by Steiger04** [ioBroker/ioBroker.scenes#56]
Um die Übersichtlichkeit für die Szenenauswahl zu verbessern schlage ich vor die einfache Liste durch einen Trieview mit subfoldern zu ersetzen / zu ergänzen. Dies trägt noch einmal deutlich zue useability bei, insbesondere wenn man eine große Anzahl von Szenen verwaltet, die schon vorkategerisiert sind. Im Objektbaum also z.B. scene.buero mit allen Büroszenen darunter, etc..

**Comment by GermanBluefox** [comment]
Ist doch mit 2.x.x gemacht. Was meinst du?
![image](https://user-images.githubusercontent.com/4582016/85208173-92253180-b32e-11ea-8ce7-c5aeddeabbbb.png)

**Comment by Steiger04** [comment]
@GermanBluefox Du hast recht. Ich hab das Icon nicht sofort gesehen. Hintergrund: ich hatte den neuen Szenen-Adapter erst jetzt installiert und er hat dann alle meine alten Szenen, die in Ordnern sortiert waren "flach" in die Liste geschrieben. Jetzt habe ich noch etwas "händisch" nachgebessert und alles ist wieder schön.
GUI gefällt mir sehr gut.
