### ISSUE TITLE
Virtuelle Gruppen funktionieren seit Update (2.0.9) nicht mehr

### ISSUE THREAD

**Issue by daniel-2k** [ioBroker/ioBroker.scenes#57]
Meine virtuellen Gruppen funktionieren jetzt nicht mehr.
Egal ob ich direkt über die Scene-Oberfläche einen Wert schreibe, oder im Objekt-Explorer direkt auf den State, er wird nicht auf die Member übertragen.
Z.B. habe ich SET_TEMPERATURE meine Heizkörperthermostate. Schreibe ich da z.B. 20 drauf steht sogar "true" auf dem State (obwohl der number ist).
Auch das Anlegen einer neuen virtuelle Gruppe zeigt das gleiche Verhalten.

**Comment by GermanBluefox** [comment]
Please test 2.0.11

**Comment by daniel-2k** [comment]
Jetzt funktioniert es zumindest, wenn ich den State im Objekt-Explorer direkt schreibe.
Wenn man es über die Oberfläche über das Eingabefeld "In virtuelle Gruppe schreiben" macht, dann scheint es nicht zu funktionieren. Er schreibt die Werte zwar, aber einige bleiben rot und werden nicht bestätigt.

**Comment by GermanBluefox** [comment]
Please test 2.0.13

**Comment by daniel-2k** [comment]
Now it's working. Thanks.

**Comment by Apollon77** [comment]
why reopen when it works now?

**Comment by daniel-2k** [comment]
was a mistake, sorry
