### ISSUE TITLE
Can't select an object in the broadlink2.0 adapter.

### ISSUE THREAD

**Issue by Anzic23** [ioBroker/ioBroker.scenes#58]
allows to select only folder.
ioBroker.scenes v 2.0.11
![image](https://user-images.githubusercontent.com/37106885/85233348-2619fa80-b40e-11ea-91fc-bbf5e99211ca.png)
![image](https://user-images.githubusercontent.com/37106885/85233385-6aa59600-b40e-11ea-81ff-faf7b8d92844.png)

**Comment by GermanBluefox** [comment]
Broadlink must be changed. States may not have leafs.

**Comment by Apollon77** [comment]
Some adapters use that for "Legacy" and "backward compatibility reasons" :-(
