### ISSUE TITLE
Bereich Szenenzustände: Liste der Objekte zeigt nur ID an

### ISSUE THREAD

**Issue by OstfrieseUnterwegs** [ioBroker/ioBroker.scenes#59]
Die Liste der Objekte sollte auch den Namen anzeigen, nicht die ID doppelt.
![2020-06-22 11_29_02-scenes - ioBroker](https://user-images.githubusercontent.com/23573740/85272237-323ca100-b47c-11ea-9d28-11acf6bbb629.png)

**Comment by GermanBluefox** [comment]
Fixed in 2.0.14

**Comment by OstfrieseUnterwegs** [comment]
Issue fixed
