### ISSUE TITLE
Komme nicht mehr in die SystemAdapter

### ISSUE THREAD

**Issue by Dirk309** [ioBroker/ioBroker.scenes#61]
Ich habe vor längerer Zeit einige Datenpunkte unter dem Javascript SystemAdapter angelegt.
Die brauche ich weiterhin für True und False.
Wie z.B. für Steckdosen und Geräte usw.
![True-False](https://user-images.githubusercontent.com/67476903/85884560-2554e000-b7e3-11ea-8a95-9ba20354b3ee.jpg)
Auch sind dort Datenpunkte für mein Sat Receiver hinterlegt.

Ich sehe keine Möglichkeit dort hin zu kommen.
Auch nicht nach dem drücken auf das Männchen Symbol....oder wie nennt man das?
![System](https://user-images.githubusercontent.com/67476903/85884964-ce033f80-b7e3-11ea-8996-ab0077495539.jpg)

**Comment by Apollon77** [comment]
JavaScript aufklappen geht nicht?

**Comment by Apollon77** [comment]
Oooohhhhh. System.adspter.javadcript?? Sehe ich jetzt erst. Da dürfen keine eigenen States liegen. Das ist das Problem. Die müssen wenn in JavaScript.0 liegen oder besser in 0_userdata.0

**Comment by Dirk309** [comment]
Man konnte immer vorher die System Adapter öffnen.
Nach drücken des Männchens (HaHa).....
Jetzt müsste ich alles umstellen....
Scripte anpassen und und und...klasse

**Comment by GermanBluefox** [comment]
Test 2.0.13

**Comment by Dirk309** [comment]
Super funzt...
Auch True/False wieder....

**Comment by Apollon77** [comment]
@Dirk309 aber BITTE überlege Dir DRINGEND die States woanders abzulegen. Keiner kann versprechen das das für immer funktioniert und das System Sie dort nicht ggf mal "automatisch aufräumt weil Sie unerwartet dort sind"!!
Die States gehören dort einfach nicht hin!
