### ISSUE TITLE
UI ist nur als "Administrator" erreichbar, nicht als User

### ISSUE THREAD

**Issue by m-s-b** [ioBroker/ioBroker.scenes#63]
Wenn ich mich im ioBroker als Administrator anmelde kann ich problemlos den Szenen-Editor öffnen.
Wenn ich mich mit meinem normalen User (ist ebenfalls in der Administrator Gruppe) anmelde sehe ich nur den Ladevorgang mit ioBroker Symbol. 
Aktuell getestet mit 2.0.15. Verhalten tritt seit Update auf das neue UI auf. (also alles größer 1.1)

**Comment by GermanBluefox** [comment]
Please check 2.1.1

**Comment by m-s-b** [comment]
Fixed, Thanks.
