### ISSUE TITLE
Intervall zwischen Befehlen wird nicht beachtet

### ISSUE THREAD

**Issue by xdaamg** [ioBroker/ioBroker.scenes#64]
Es wurde mit einer früheren Version des Szenen-Adapters eine Szene mit 5 Befehlen erzeugt. Es wurde ein "Intervall zwischen Befehlen" von 5000 ms festgelegt. Mit der aktuellen Version werden alle Befehle ohne erkennbare Verzögerung "gleichzeitig" ausgeführt. Bekannter Fehler? Oder müssen die Szenen mit der neuen Version neu erstellt werden, damit alles funktioniert?

**Comment by GermanBluefox** [comment]
Will be fixed in 2.1.0

**Comment by xdaamg** [comment]
Erfolgreich getestet, Fehler behoben
