### ISSUE TITLE
How to use Node-RED to switch ioBroker scenes

### ISSUE THREAD

**Issue by mtoensing** [ioBroker/ioBroker.scenes#66]
I try to switch a iobroker scene. I successfully receive a boolean from my alexa node-red node. I can see the output of msg.payload with the debug node. That switches from true to false and vice-versa if I use the alexa command. The connected scenes can be switch on/off manually in iobroker.

How do I control the scene with the true/false of the alexa node? What part am I missing? What does the scene need as input?

<img width="985" alt="Screen Shot 2020-07-18 at 10 36 57" src="https://user-images.githubusercontent.com/136737/87848762-5a84b780-c8e3-11ea-9955-db19fae294aa.png">

**Comment by mtoensing** [comment]
Since scenes did not work I use the devices directly. Work out of the box.
<img width="674" alt="Screen Shot 2020-07-18 at 22 08 52" src="https://user-images.githubusercontent.com/136737/87873072-8e80db00-c9be-11ea-8a8d-e6d33d6caa62.png">

**Comment by mtoensing** [comment]
But I am still curious how to fix that. =)

**Comment by Apollon77** [comment]
node-red has currently an issue if state ids are not like "scenes.0.name" ... as in your case ... see https://github.com/ioBroker/ioBroker.node-red/issues/102#issuecomment-654983682
