### ISSUE TITLE
Keine Datenpunkte 2 fach

### ISSUE THREAD

**Issue by michad2** [ioBroker/ioBroker.scenes#68]
Moin,
ich kann bei der aktuellen Version keine Datenpunkte 2 mal hinzufügen, also mehrfach.
Wollte eine Szene erstellen die das Licht erst auf 10 % einschaltet, 2 Sekunden später auf 20 %.
Wenn ich aber den Datenpunkt nochmals hinzufügen will kommt "Unknown error".
Bei  der alten Version 1.xx ging das. 
Auch die mit der alten Version erstellten Szenen funktionieren

Gruß Micha

**Comment by GermanBluefox** [comment]
Fixed in 2.2.0
