### ISSUE TITLE
Undefined values for "setpoint FALSE" sets them to "false"

### ISSUE THREAD

**Issue by agross** [ioBroker/ioBroker.scenes#69]
I do not know whether this is intended, so this is rather a question than a bug report.

* I have a scene that I use to enable and disable lights when I enter a room (i.e. "set value if false" is checked).
* When the room is entered I want to set a light's brightness to a certain value and also the light's state to `true`.
* When the room is left, I do not care about the light's brightness but its state should be set to `false`.

![image](https://user-images.githubusercontent.com/16245/92364422-59a62000-f0f3-11ea-80fe-7b6650eb6f76.png)

The relevant bit of JSON:
```jsonc
"members": [
  {
    "id": "zigbee.1.680ae2fffea72a25.brightness",
    "setIfTrue": 100,
    "setIfFalse": null,
    "stopAllDelays": true,
    "desc": null
  },
  // transition time here
  {
    "id": "zigbee.1.680ae2fffea72a25.state",
    "setIfTrue": true,
    "setIfFalse": false,
    "stopAllDelays": true,
    "desc": null
  }
]
```

Note the light's `"setIfFalse": null` setting.

When the scene is enabled, the light's brightness is set to `100` as per ioBroker's object tree. When the scene is set to `false` the light's brightness is set to `false`, which does not make sense to me:

* A light's brightness (`level.dimmer` with `"type": "number"`) cannot be `false`
* `setIfFalse` is defined as `null`, my impression is that the Scenes adapter should not touch the state because no value is defined.

I tested the same with the transition time (second state in the screenshot above, also a `number`) and it will also set its value to `false sec` (in the UI):

![image](https://user-images.githubusercontent.com/16245/92365615-5a8b8180-f0f4-11ea-9526-6207389d0a86.png)

**Comment by GermanBluefox** [comment]
Fixed in 2.2.0
Actually value=null was an error and must never happen... But now let's see what will happen.
