### ISSUE TITLE
Drag n drop is not working properly if two items have the same object ID

### ISSUE THREAD

**Issue by mswiege** [ioBroker/ioBroker.scenes#70]
To reproduce:
Add some multiple states to your scene.
Two of those states should use the same object id
Try to reorder the states (those with the same ID or try to place others above/below/between them) via drag n drop.

The issue seems to be that the object ID is used as identifier during the drag n drop and therefore isn't unique if multiple items with the same object ID exist.

**Comment by GermanBluefox** [comment]
Fixed in 2.2.0
