### ISSUE TITLE
Keine Ordnerüberschriften vorhanden

### ISSUE THREAD

**Issue by Whilk-and-Misky** [ioBroker/ioBroker.scenes#71]
Gude,

bei mir sind in der Auswahlübersicht zum hinzufügen von Geräten keine Ordnerüberschriften vorhanden. Somit erkennt man z.B. im Zigbee Adapter nicht, um welches Gerät es sich handelt. Verion 2.1.3.

Gruß, Steffen

![image](https://user-images.githubusercontent.com/33321734/94000634-b9f5bc80-fd97-11ea-8596-5ac31866422c.png)

**Comment by GermanBluefox** [comment]
Ist das auch in 2.1.7 zu sehen?

**Comment by GermanBluefox** [comment]
Fixed at least in 2.3.0
![Uploading image.png…]()
