### ISSUE TITLE
"Add new state" not working in 2.1.7

### ISSUE THREAD

**Issue by boardnick0815** [ioBroker/ioBroker.scenes#72]
**Describe the bug**  
If you try to add a new state by clicking the "+" icon you get a blank page and not the objects selection.

**To Reproduce**  
1. Go to 'Scenes'
2. Create a new scene
3. Click on "+" / Add new state

**Expected behavior**  
Appearing of a popup with available objects

**Versions:**  
 - Adapter version: 2.1.7
 - JS-Controller version: 3.1.6
 - Node version: 12.19.0
 - Operating system: Debian Buster

**Additional context**  
see also: [forum entries](https://forum.iobroker.net/topic/38187/scenes-adapter-neuen-zustand-hinzufügen-nicht-möglich)

**Comment by spitfire4all** [comment]
Same here

**Comment by nukleuz80** [comment]
Same issue here:

Setup:

- Adapter version: 2.1.7
- JS-Controller version: 3.1.6
- Node version: 12.19.0
- Operating system: Debian Buster

**Comment by Matt77CHE** [comment]
Same here

**Comment by Holger76** [comment]
Same here, 
back to 2.1.2 (other not tried) and it works.

**Comment by Elexil** [comment]
Same here with 2.17

**Comment by GermanBluefox** [comment]
Fixed in 2.2.0

**Comment by Matt77CHE** [comment]
Nice, but there is no 2.2.0 - only 2.1.7 ......

**Comment by Matt77CHE** [comment]
Nice, but there is no 2.2.0 in iOBroker adapters  - only 2.1.7 ......
