### ISSUE TITLE
Update auf 2.3.1 geht nicht 

### ISSUE THREAD

**Issue by EduardSarjadjuk** [ioBroker/ioBroker.scenes#73]
Hallo Zusammen, 
Das Update auf 2.3.1 funktioniert bei mir nicht. Nachdem die Installation durchgelaufen ist, steht der Adapter immer noch auf der alten Version.
Nodejs 12.19.0
Jscontroller 3.1.6

Mache ich etwas falsch ?

**Comment by GermanBluefox** [comment]
`iobroker u scenes`

**Comment by McWoolf** [comment]
Sorry ich versteh das nicht.
Bei mir kann ich zwar eine scene erstellen und abspeichern, aber wenn ich testen will, sagt es mir "instanz läuft nicht"
wenn ich dann bei der instanz nachsehe, ist diese auf rot. nach kurzer zeit wird sie aber wieder grün. beim test dann wieder rot.
Ich weiss nicht mehr weiter.
