### ISSUE TITLE
Nach Update auf 2.3.1 kein Edit mehr mehr möglich

### ISSUE THREAD

**Issue by oke24** [ioBroker/ioBroker.scenes#74]
Nach dem Update auf V. 2.3.1 lassen sich die Zustände nicht mehr editieren.
Auch das Ein/Aus- Schalten der Scene funktinoniert bei mir nicht mehr.

![image](https://user-images.githubusercontent.com/46261409/98439381-e2403d00-20f1-11eb-880d-4cf43c8588dc.png)

**Comment by denzel1994** [comment]
Bei mir wird sogar der Szenenzustand nicht korrekt erkannt.
Alles Geräte auf true, aber Szenenzustand auf false. „False Testen“ funktioniert dann auch nicht.

**Comment by GermanBluefox** [comment]
Es gibt kein Edit mehr. Dafür gibt es:
![image](https://user-images.githubusercontent.com/4582016/98518891-50127300-2270-11eb-8bc8-0590ba361560.png)

**Comment by GermanBluefox** [comment]
Auch in dieser Version muss man False explizit setzten. Da sieht man, dass FALSE auf null steht:
![image](https://user-images.githubusercontent.com/4582016/98532537-1cd8df80-2282-11eb-8bd1-9b47a0c35850.png)

Wenn False gesetzt ist, dann sieht es so aus:
![image](https://user-images.githubusercontent.com/4582016/98532595-34b06380-2282-11eb-8a68-6ededc8697b8.png)

**Comment by oke24** [comment]
vielen Dank für die beiden Hinweise ! Nach Setzen von true und false scheinen alle Szenen wieder zu funktionieren.
