### ISSUE TITLE
Löschen with "Enter"

### ISSUE THREAD

**Issue by obodeldog** [ioBroker/ioBroker.scenes#77]
It would be good if you could simply press "Enter" to confirm the "Delete". If you want to delete 20 objects, you have to move the mouse back and forth.
![image](https://user-images.githubusercontent.com/35403739/101132991-36aedd80-3608-11eb-8aa9-73c7b34773c9.png)

**Comment by GermanBluefox** [comment]
Implemented in 2.3.2
