### ISSUE TITLE
Possibility of using average (and other logics) in virtual groups

### ISSUE THREAD

**Issue by siggi85** [ioBroker/ioBroker.scenes#79]
How it works now:
When all dapatoints of a virtual group have not the same value, the virtual datapoint get the value "uncertain" at the moment. 

Feature Request:
It would be great to have some more options for that behaviour. The most basic one should be, show the average of all datapoints.
For example: This is useful when you group some brightness datapoints of one room. When 2 lamps are 100% and other 2 lamps are 50%, it would be great when the virtual datapoint would be 75%. So the Datapoint would look good in VIS and can be used for some brightness logic.

Other logic would be OR or AND Logic.
OR - Datapoint is true, when **one** of the group members is true. Otherwise it is false.
AND - Datapoint is true, when **all** of the group members are true. Otherwise it is false.

Example for the AND logic: the state datapoints of multiple lamps in one room. When one lamp is on, the light in the room is considerd on.

**Comment by TyrionWarMage** [comment]
#93
