### ISSUE TITLE
States so lassen wie sie sind 

### ISSUE THREAD

**Issue by thorque** [ioBroker/ioBroker.scenes#9]
Hallo,

bisher ist es so, dass ich in der Konfiguration der States einer Szene entscheiden muss, soll sie auf true oder false. Oft wäre es praktisch, den state so zu lassen wie er ist. Bei Beleuchtung ist das oft wünschenswert, damit man nicht plötzlich im dunklen steht.

Beispiel:
Szene Guten Morgen. Steuere ich die Szene mit dem Astro-Timer, dann will ich nicht, dass im Sommer um 4:00 Uhr das Licht im Schlafzimmer angeht. Im Winter habe ich die Lampe aber bereits um 6:00 angemacht, während der Sonnenaufgang erst um 06:30 ist. In dem fall, soll der Status ignoriert werden.

Das wäre noch extrem praktisch und würde die Mächtigkeit der Szenen noch erweitern.

**Comment by GermanBluefox** [comment]
Ist im 2.0.1 implementiert

**Comment by louisvangeldrop** [comment]
Can you please give an example how to schedule based on the astro-function.
