### ISSUE TITLE
After upgrade to js-controller 3.3.x

### ISSUE THREAD

**Issue by cracyfloyd** [ioBroker/ioBroker.scenes#96]
Warnings in LOG:

scenes.0 | 2021-04-30 12:29:16.263 | warn | State value to set for "scene.0.Terrasse_-_Normal" has wrong type "string" but has to be "boolean"
-- | -- | -- | --
scenes.0 | 2021-04-30 12:29:15.785 | warn | State value to set for "scene.0.Terrasse_-_Normal" has wrong type "string" but has to be "boolean"
scenes.0 | 2021-04-30 12:29:15.784 | warn | State value to set for "scene.0.Terrasse_-_Gemütlich" has wrong type "string" but has to be "boolean"
scenes.0 | 2021-04-30 12:29:15.162 | warn | State value to set for "scene.0.0_Szene_Hausbeleuchtung" has wrong type "string" but has to be "boolean"
scenes.0 | 2021-04-30 12:29:13.954 | warn | State "deconz.0.lights.7cb03eaa0a02ea2a7.level" has no existing object, this might lead to an error in future versions
scenes.0 | 2021-04-30 12:29:13.863 | warn | State "deconz.0.lights.7cb03eaa0a02ea2a0.level" has no existing object, this might lead to an error in future versions
scenes.0 | 2021-04-30 12:29:13.554 | warn | State "deconz.0.lights.0017880104ba0c0a.on" has no existing object, this might lead to an error in future versions
scenes.0 | 2021-04-30 12:29:13.484 | warn | State value to set for "scene.0.WZ-Couch-100" has wrong type "string" but has to be "boolean"
scenes.0 | 2021-04-30 12:29:13.254 | warn | State "deconz.0.lights.7cb03eaa0a02ea2a7.on" has no existing object, this might lead to an error in future versions
scenes.0 | 2021-04-30 12:29:13.154 | warn | State "deconz.0.lights.7cb03eaa0a02ea2a0.on" has no existing object, this might lead to an error in future versions
scenes.0 | 2021-04-30 12:29:12.351 | warn | State "sonoff.0.Sonoff-Lichtbogen.POWER" has no existing object, this might lead to an error in future versions
scenes.0 | 2021-04-30 12:29:12.265 | warn | State value to set for "scene.0.0_Szene_WZ/_EZ/DI_100" has wrong type "string" but has to be "boolean"
scenes.0 | 2021-04-30 12:29:12.264 | warn | State value to set for "scene.0.0_Szene_WZ/EZ100" has wrong type "string" but has to be "boolean"
scenes.0 | 2021-04-30 12:29:12.263 | warn | State value to set for "scene.0.0_Szene_Hausbeleuchtung" has wrong type "string" but has to be "boolean"
scenes.0 | 2021-04-30 12:29:12.262 | warn | State value to set for "scene.0.0_Szene_Abends" has wrong type "string" but has to be "boolean"
scenes.0 | 2021-04-30 12:28:56.257 | warn | State "deconz.0.lights.0017880104ba0c0a.on" has no existing object, this might lead to an error in future versions
scenes.0 | 2021-04-30 12:28:55.052 | warn | State "sonoff.0.Sonoff-Lichtbogen.POWER" has no existing object, this might lead to an error in future versions
scenes.0 | 2021-04-30 12:28:54.960 | warn | State value to set for "scene.0.0_Szene_Hausbeleuchtung" has wrong type "string" but has to be "boolean"

**Comment by Apollon77** [comment]
Hm ... thats interesting ... In fact you configure teh scenes states yourself. Pleasse make first sure that tjs configuration is corredct!
It seems you have configured here states that do not exists (has no object) ior you created scene values with other dstatypes then the states ...

I can not see what scenes can do here better (beside hindering you from creation of this ....
Can you check your config please first?

**Comment by GermanBluefox** [comment]
Please try 2.3.7
